//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;settings&gt;
        ///&lt;servers&gt;
        ///&lt;server url=&quot;http://speedtest.pronea.no/speedtest/upload.php&quot; lat=&quot;69.6828&quot; lon=&quot;18.9428&quot; name=&quot;Tromso&quot; country=&quot;Norway&quot; countrycode=&quot;NO&quot; sponsor=&quot;Pronea AS&quot; sponsorurl=&quot;http://www.pronea.no/&quot; id=&quot;1327&quot; gid=&quot;0&quot; url2=&quot;http://speedtest.pronea.no/speedtest/upload.php&quot; bigsamples=&quot;1&quot;/&gt;
        ///&lt;server url=&quot;http://speedtest.mmsn.ru/speedtest/upload.php&quot; lat=&quot;68.9667&quot; lon=&quot;33.0833&quot; name=&quot;Murmansk&quot; country=&quot;Russian Federation&quot; countrycode=&quot;RU&quot; sponsor=&quot;JSC M2C&quot; sponsorurl=&quot;http://www.mmsn.ru&quot; id=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
    }
}
